new day new task

diff --git a/.github/workflows/DEVLOPER_PIPELINE.yaml b/.github/workflows/DEVLOPER_PIPELINE.yaml
--- a/.github/workflows/DEVLOPER_PIPELINE.yaml
+++ b/.github/workflows/DEVLOPER_PIPELINE.yaml
@@ -1,5 +1,10 @@
 name: DEV-PIPELINE
 on:
+  push:
+    branches:
+      - qa
+      - uat
+      - main
   pull_request:
     branches:
       - qa
@@ -9,7 +14,7 @@ on:
       - "force-app/**"
 jobs:
   validate:
-    if: github.event_name == 'pull_request'
+    if: github.event_name == 'pull_request' || github.event_name == 'push'
     runs-on: ubuntu-latest
 
     steps:
@@ -41,7 +46,8 @@ jobs:
         run: |
           echo Y | sf plugins install sfdx-git-delta
           sf plugins
-
+      
+      # Delta Creation
       - name: Create Delta changes for validation
         id: delta
         run: |
@@ -53,6 +59,10 @@ jobs:
             SRC_COMMIT="${{ github.event.pull_request.head.sha }}"
             TGT_COMMIT="${{ github.event.pull_request.base.sha }}"
             TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
+            else
+            SRC_COMMIT=$(git rev-parse HEAD)
+            TGT_COMMIT=$(git rev-parse HEAD~1)
+            TARGET_BRANCH="${GITHUB_REF#refs/heads/}"
           fi
 
           if [ -z "$SRC_COMMIT" ] || [ -z "$SRC_COMMIT" ]; then
@@ -69,6 +79,7 @@ jobs:
           fi
 
           echo "Running delta creation command"
+          echo "Creating Delta package From Commit : $FROM_COMMIT To : $TO_COMMIT"
           sf sgd source delta --to "$TO_COMMIT" --from "$FROM_COMMIT" --output delta/ --generate-delta --source force-app/
 
           if [ ! -d "delta/force-app" ] || [ -z "$(ls -A delta/force-app)" ]; then
@@ -84,6 +95,8 @@ jobs:
             echo "NO_CHANGES=false" >> $GITHUB_OUTPUT
             echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_OUTPUT
           fi
+
+      # PMD SCAN
       - name: RUN PMD SCAN
         run: |
           chmod +x ./pmd/pmd-bin-7.7.0/bin/pmd
@@ -92,6 +105,7 @@ jobs:
             -R rulesets/apex/quickstart.xml \
             -f text || true
 
+      # Authentication
       - name: Authenticate to org
         id: auth
         if: steps.delta.outputs.NO_CHANGES == 'false'
@@ -120,7 +134,8 @@ jobs:
           sf org login sfdx-url --sfdx-url-file authfile.txt --alias "$ALIAS" --set-default
           echo "ALIAS=$ALIAS" >> $GITHUB_OUTPUT
           rm authfile.txt
-
+      
+      # Extracting test classes
       - name: Extract Test classes
         id: test
         if: steps.delta.outputs.NO_CHANGES == 'false'
@@ -178,7 +193,8 @@ jobs:
 
           echo "TEST_LIST=$TEST_LIST" >> $GITHUB_OUTPUT
 
-      - name: Validate the steps.auth.outputs.ALIAS org
+      # validation 
+      - name: Validate the ${{ steps.auth.outputs.ALIAS }} org
         if: steps.delta.outputs.NO_CHANGES == 'false'
         run: |
           ALIAS="${{ steps.auth.outputs.ALIAS }}"
@@ -211,6 +227,134 @@ jobs:
               -l NoTestRun
           fi 
 
+  Deployment:
+    needs: validate
+    if: github.event.name='push' 
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Install repo
+        uses: actions/checkout@v3
+        
+      - name: Install Node.js
+        uses: actions/node
+        with:
+          node-version: '22'  
+        
+      - name: Install SFDX 
+        run: npm install @salesforce/cli --global
+
+      - name: Install PMD
+        run: |
+          echo "Downloading PMD..."
+          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.7.0/pmd-dist-7.7.0-bin.zip
+          unzip pmd.zip -d pmd
+          echo "PMD extracted:"
+          ls -R pmd
+      
+      - name: Install xmllint
+        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
+
+      - name: Install sfdx-git-delta
+        run: |
+          echo Y | sf plugins install sfdx-git-delta
+          sf plugins 
+      
+      - name: Set Branch Environment
+        id: env
+        run: |
+          RAW_BRANCH="${GITHUB_REF#refs/heads/}"
+          if [[ "$RAW_BRANCH" == "qa" ]]; then
+            echo "ORG_AUTH_URL=${{ secrets.SFDX_AUTH_URL_QA }}" >> $GITHUB_OUTPUT
+            echo "ENV_NAME=QA" >> $GITHUB_OUTPUT
+            echo "DEPLOY_TAG_PREFIX=qa-deployed" >> $GITHUB_OUTPUT
+          elif [[ "$RAW_BRANCH" == "uat" ]]; then
+            echo "ORG_AUTH_URL=${{ secrets.SFDX_AUTH_URL_UAT }}" >> $GITHUB_OUTPUT
+            echo "ENV_NAME=UAT" >> $GITHUB_OUTPUT
+            echo "DEPLOY_TAG_PREFIX=uat-deployed" >> $GITHUB_OUTPUT
+          elif [[ "$RAW_BRANCH" == "main" ]]; then
+            echo "ORG_AUTH_URL=${{ secrets.SFDX_AUTH_URL_PROD }}" >> $GITHUB_OUTPUT
+            echo "ENV_NAME=PROD" >> $GITHUB_OUTPUT
+            echo "DEPLOY_TAG_PREFIX=prod-deployed" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: Unsupported branch $RAW_BRANCH"
+            exit 1
+          fi
+
+      # Searching for last deployment tag
+      - name: Find last deployment tag
+        id: last_tag
+        run: |
+          LAST_TAG=$(git describe --tags --abbrev=0 --match "${{ steps.env.outputs.DEPLOY_TAG_PREFIX}}/*" 2>/dev/null || true)
+          if [ -z "$LAST_TAG" ]; then
+            echo "Unable To Find Tags"   
+            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
+
+            echo "Fetching remote branch: $BRANCH_NAME"
+            git fetch origin "$BRANCH_NAME:$BRANCH_NAME"
+
+            MERGE_BASE=$(git merge-base HEAD origin/$BRANCH_NAME)
+            FROM=$MERGE_BASE
+
+          else
+            echo "Tags Found Successfully"
+            FROM=$(git rev-list -n 1 "$LAST_TAG")
+          fi
+
+          echo "FROM_COMMIT=$FROM" >> $GITHUB_OUTPUT
+          echo "TO_COMMIT=HEAD" >> $GITHUB_OUTPUT
+      
+      # Delta Creation
+      - name: Create delta for deployment
+        id: delta_deploy
+        run: |
+          mkdir delta
+
+          sf sgd source delta \
+            --from "${{ steps.last_tag.outputs.FROM_COMMIT }}" \
+            --to "HEAD" \
+            --output delta/ \
+            --generate-delta \
+            --source force-app/ 
+
+          if [ ! -d "delta/force-app" ] || [ -z "$(ls -A delta/force-app)" ]; then
+            echo "NO_CHANGES=true" >> $GITHUB_OUTPUT
+          else
+            echo "NO_CHANGES=false" >> $GITHUB_OUTPUT
+          fi
+
+      # Authenticate
+      - name: Authentication
+        if: steps.delta_deploy.outputs.NO_CHANGES == 'false'
+        run: |
+          echo "${{ steps.env.outputs.ORG_AUTH_URL }}" > authfile.txt
+          sf org login sfdx-url --sfdx-url-file authfile.txt --alias "${{ steps.env.outputs.ENV_NAME }}" --set-default
+          rm authfile.txt
+          echo "Authenticated to org: ${{ steps.env.outputs.ENV_NAME }}"  
+
+      
+      # Delta Deployment
+      - name: Deployment
+        if: steps.delta_deploy.outputs.NO_CHANGES == 'false'
+        run: |
+          sf project deploy start \
+            --manifest delta/package/package.xml \
+            --target-org "${{ steps.env.outputs.ENV_NAME }}"\
+            --test-level RunLocalTests 
+
+      # Tag creation
+      - name: Tag deployment
+        if: steps.delta_deploy.outputs.NO_CHANGES == 'false'
+        run: |
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git config user.name "GitHub Actions Bot"
+
+          TAG="${{ steps.env.outputs.DEPLOY_TAG_PREFIX }}/${{ github.sha }}"
+          git tag -a "$TAG" -m "Deployed ${{ github.sha }} to ${{ steps.env.outputs.ENV_NAME }}"
+          git push origin "$TAG" 
+
+
+          
 
 
 
