nothing changed

diff --git a/.github/workflows/test2.yaml b/.github/workflows/test2.yaml
--- a/.github/workflows/test2.yaml
+++ b/.github/workflows/test2.yaml
@@ -509,10 +509,9 @@ jobs:
   Deploy:
     needs: validate
     #needs: [code-quality]
-    if: github.event_name == 'push' && github.ref == 'refs/heads/uat'
+    if: github.event_name == 'push' && (github.ref == 'refs/heads/qa' || github.ref == 'refs/heads/uat' || github.ref == 'refs/heads/main')
     runs-on: ubuntu-latest
-    environment: uat
-
+  
     steps:
       - name: Checkout full repo
         uses: actions/checkout@v3
@@ -523,6 +522,7 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '18'
+
       - name: Install Salesforce CLI
         run: npm install @salesforce/cli --global
 
@@ -530,14 +530,35 @@ jobs:
         run: |
           echo Y | sf plugins install sfdx-git-delta
           sf plugins
+      
+      - name: Set Branch Environment
+        id: env
+        run: |
+          RAW_BRANCH="${GITHUB_REF#refs/heads/}"
+          if [[ "$RAW_BRANCH" == "qa" ]]; then
+            echo "ORG_AUTH_URL=${{ secrets.SFDX_AUTH_URL_QA }}" >> $GITHUB_OUTPUT
+            echo "ENV_NAME=QA" >> $GITHUB_OUTPUT
+            echo "DEPLOY_TAG_PREFIX=qa-deployed" >> $GITHUB_OUTPUT
+          elif [[ "$RAW_BRANCH" == "uat" ]]; then
+            echo "ORG_AUTH_URL=${{ secrets.SFDX_AUTH_URL_UAT }}" >> $GITHUB_OUTPUT
+            echo "ENV_NAME=UAT" >> $GITHUB_OUTPUT
+            echo "DEPLOY_TAG_PREFIX=uat-deployed" >> $GITHUB_OUTPUT
+          elif [[ "$RAW_BRANCH" == "main" ]]; then
+            echo "ORG_AUTH_URL=${{ secrets.SFDX_AUTH_URL_PROD }}" >> $GITHUB_OUTPUT
+            echo "ENV_NAME=PROD" >> $GITHUB_OUTPUT
+            echo "DEPLOY_TAG_PREFIX=prod-deployed" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR: Unsupported branch $RAW_BRANCH"
+            exit 1
+          fi 
 
       # Determine Correct Commit Range Using Tags
       # if not tag exists FROM=$(git rev-list --max-parents=0 HEAD) this takes root commit from the head ex: A-->Root Commit B C D-->latest commit  then From Becomes commit A
       # if tags exists FROM=$(git rev-list -n 1 "$LAST_TAG") then checks this tag is related to which commit lets say it was commit A then from Becomes A
-      - name: Find last UAT deployment tag
+      - name: Find last deployment tag
         id: last_tag
         run: |
-          LAST_TAG=$(git describe --tags --abbrev=0 --match "uat-deployed/*" 2>/dev/null || true)
+          LAST_TAG=$(git describe --tags --abbrev=0 --match "${{ steps.env.outputs.DEPLOY_TAG_PREFIX}}" 2>/dev/null || true)
           if [ -z "$LAST_TAG" ]; then
             FROM=$(git rev-list --max-parents=0 HEAD)    
           else
@@ -548,7 +569,7 @@ jobs:
           echo "TO_COMMIT=HEAD" >> $GITHUB_OUTPUT
 
       # Delta for main deployment
-      - name: Create delta for UAT deployment
+      - name: Create delta for deployment
         id: delta_deploy
         run: |
           mkdir changed-sources
@@ -570,14 +591,10 @@ jobs:
       - name: Authenticate to UAT
         if: steps.delta_deploy.outputs.NO_CHANGES == 'false'
         run: |
-          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
-          sf org login jwt \
-            --username "${{ secrets.DEPLOYMENT_USER_NAME }}" \
-            --jwt-key-file server.key \
-            --client-id "${{ secrets.CONSUMER_KEY }}" \
-            --instance-url "${{ vars.INSTANCE_URL }}" \
-            --set-default
-          rm server.key  
+          echo "${{ steps.env.outputs.ORG_AUTH_URL }}" > authfile.txt
+          sf org login sfdx-url --sfdx-url-file authfile.txt --alias "${{ steps.env.outputs.ENV_NAME }}" --set-default
+          rm authfile.txt
+          echo "Authenticated to org: ${{ steps.env.outputs.ENV_NAME }}"
 
       # Deploy Delta to UAT
       
@@ -586,6 +603,7 @@ jobs:
         run: |
           sf project deploy start \
             --source-dir changed-sources/force-app \
+            --target-org "${{ steps.env.outputs.ENV_NAME }}"
             --test-level RunLocalTests 
 
       # Tag Deployment
@@ -596,7 +614,7 @@ jobs:
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git config user.name "GitHub Actions Bot"
 
-          TAG="uat-deployed/${{ github.sha }}"
-          git tag -a "$TAG" -m "Deployed ${{ github.sha }} to UAT"
+          TAG="${{ steps.env.outputs.DEPLOY_TAG_PREFIX }}/${{ github.sha }}"
+          git tag -a "$TAG" -m "Deployed ${{ github.sha }} to ${{ steps.env.outputs.ENV_NAME }}"
           git push origin "$TAG"
 
